# Generated by Django 4.0.3 on 2022-09-28 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=60)),
                ('comissão', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=9)),
                ('corretor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Atividade_3.corretor')),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('corretores', models.ManyToManyField(to='Atividade_3.corretor')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=300)),
                ('regiao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Atividade_3.regiao')),
            ],
        ),
        migrations.CreateModel(
            name='CGerenciaC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpfCorretor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Gerenciado', to='Atividade_3.corretor')),
                ('cpfGerente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Gerente', to='Atividade_3.corretor')),
            ],
        ),
    ]
