# Generated by Django 4.0.3 on 2022-09-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atividade_3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corretor',
            old_name='comissão',
            new_name='comissao',
        ),
        migrations.CreateModel(
            name='CorretorARegiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corretor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Atividade_3.corretor')),
                ('regiao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Atividade_3.regiao')),
            ],
        ),
    ]
